// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgnqbsxvtxnkykhhdddc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbnFic3h2dHhua3lraGhkZGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4Mzc1OTIsImV4cCI6MjA3MTQxMzU5Mn0.xIajxazTwJ6Ri_2TiJPDqQqdBXc3aB3z1jDghPY48Xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});